config/routes.rb
Rails.application.routes.draw do
 root to: "tweets#index"
 devise_for :users

 resources :tweets
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  validates :body, presence: true
  validates :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = current_user.tweets.create(tweet_params)

    if @tweet.save
      flash[:notice] = "Tweet successfully submitted"
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
      end
    else
      render :new
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to root_path
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twittre</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <ul class="nav navbar-nav navbar-left">
        <a class="navbar-brand" href="/">Tweetre</a>
      </ul>

      <ul class="nav navbar-nav navbar pull-right">
        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete, id: "log_out" %></li>
          <li><%= link_to "Tweet", new_tweet_path, id: "create_tweet", remote:true %></li>

        <% else %>
          <li> <%= link_to "Sign up", new_user_registration_path, id: "sign_up" %> </li>
          <li> <%= link_to "Sign in", new_user_session_path, id: "sign_in" %> </li>
        <% end %>
      </ul>
    </nav>

    <% if user_signed_in? %>
      <p class="right-align">Logged in as <%= current_user.email %></p>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="col-md-10 offset-1" id="main-content">
      <%= yield %>
    </div>

  </div>

</body>
</html>

app/views/tweets/_form.html.erb
<div id="form_errors">
  <%= render "layouts/errors", object: @tweet %>
  <%= form_for @tweet, remote:true do |f| %>
    <p>
      <%= f.label "Author a new tweet" %>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit id: "submit" %>
    </p>
  <% end %>
</div>

app/views/tweets/create.js.erb
$('#form_errors').remove();
$('#index').show();
$('#tweet_list').append('<li><%= @tweet.body %></li>');

app/views/tweets/index.html.erb
<div id="index">
  <h2>TWEETS</h2>
  <ul id="tweet_list">
    <% @tweets.each do |tweet| %>
      <li><%= tweet.body %></li>
    <% end %>
  </ul>
</div>

app/views/tweets/new.js.erb
$('#form_errors').remove();
$('#index').hide().after('<%= j render('form') %>');